package test;

import blastConnetor.NoBlastConnectionException;
import blastConnetor.proteinBlast;
import orFinderApp.ORF;
import orFinderApp.Query;

import java.net.ConnectException;

public class testClass {
    public static String SEQ = "RNQSVLSLYKTSDVFRLPEKLQSSNSSKNQRSPSMLLFPDNTSNVYSKHRIAKEPSVDNESEDMS" +
            "DSKQKISHLSKVTLVSTLMKGVDYPSSYAVDKIMPPTPAKKVEFILNSLYIPEDLNEQSGTLQGTSTTSS" +
            "LDNNSNSNSRSNTSSMSVLHRSAIGLLAKWMKNHNRHDSSNDKKFMSAIKPANQKPEMDAFVKYVVSISS" +
            "LNRKSSKEEEEEFLNSDSSKFDILSARTIDEVESLLHLQNQLIEKVQTHSNNNRGPTVNVDCERREHIHD" +
            "IKILQQNSFKPSNDNFSAMDNLDLYQTVSSIAQSVISLTNTLNKQLQNNESNMQPSPSYDALQRRKVKSL" +
            "TTAYYNKMHGSYSAESMRLFDKDNSSSRTDENGPQRLLFHETDKTNSEAITNMTPRRKNHSQSQKSMTSS" +
            "PLKNVLPDLKESSPLNDSREDTESITYSYDSELSSSSPPRDTVTKKSRKVRNIVNNTDSPTLKTKTGFLN" +
            "LREFTFEDTKSLDEKKSTIDGLEKNYDNKENQESEYESTKKLDNSLDASSEANNYDITTRKKHSSCNHKI" +
            "KQAVVRPASGRISISRVQSIAITPTKELSIVDPEQNKSNSVIEEISEIEPLNLEYNKKSALYSDTSSTVI" +
            "SISTSKLFESAQNSPLKQTQNPQREFPNGTSVSETNRIRLSIAPTIESVVSDLNSITTGSTVETFETSRD" +
            "LPVPHQRIINLREEYQRGNQDIISNTSSLHELKTIDLSDSNNDLESPSTHAKNNKYFFSPDDGSIDVASP" +
            "MKNVEELKSKFLKNESETNSNISGSVLTMDDIDINDTSSARNTRRANSESAFTGSLNKKNLNEIANMLDD" +
            "SINDDPITVALMKLEGTYEKIPEKPENTKSSDAIGIKTSKLADEVEMLNLNNLPSFQNSPAEKRKSLLIE" +
            "RRRQTIMNIPFTPDQSEKEGFTSSSPEKIDVSANVDVAVQAAQIQELIGQYRIHDSRLMISNNESHVPFI" +
            "LMYDSLSVAQQMTLIEKEILGEIDWKDLLDLKMKHEGPQVISWLQLLVRNETLSGIDLAISRFNLTVDWI" +
            "ISEILLTKSSKMKRNVIQRFIHVADHCRTFQNFNTLMEIILA";

    public static void main(String[] args) {
        Query query = new Query("test header", SEQ);
        ORF newOrf = new ORF(400, 600);
        ORF newOrf2 = new ORF(50, 400);
        query.addOrfList(newOrf);
        query.addOrfList(newOrf2);
        proteinBlast testBlast = new proteinBlast();

        try {
            System.out.println("Threads worden aangezet");
            testBlast.proteinBlast(query);
            System.out.println("Alle Threads zijn klaar");

        } catch (NoBlastConnectionException nbce){

        } catch (InterruptedException e){
            System.out.println(e.getMessage());
        }

    }
}
