package test;

import blastConnetor.proteinBlast;
import orFinderApp.ORF;
import orFinderApp.Query;

public class testClass {
    public static String SEQ = "RNQSVLSLYKTSDVFRLPEKLQSSNSSKNQRSPSMLLFPDNTSNVYSKHRIAKEPSVDNESEDMS" +
            "DSKQKISHLSKVTLVSTLMKGVDYPSSYAVDKIMPPTPAKKVEFILNSLYIPEDLNEQSGTLQGTSTTSS" +
            "LDNNSNSNSRSNTSSMSVLHRSAIGLLAKWMKNHNRHDSSNDKKFMSAIKPANQKPEMDAFVKYVVSISS" +
            "LNRKSSKEEEEEFLNSDSSKFDILSARTIDEVESLLHLQNQLIEKVQTHSNNNRGPTVNVDCERREHIHD" +
            "IKILQQNSFKPSNDNFSAMDNLDLYQTVSSIAQSVISLTNTLNKQLQNNESNMQPSPSYDALQRRKVKSL" +
            "TTAYYNKMHGSYSAESMRLFDKDNSSSRTDENGPQRLLFHETDKTNSEAITNMTPRRKNHSQSQKSMTSS" +
            "PLKNVLPDLKESSPLNDSREDTESITYSYDSELSSSSPPRDTVTKKSRKVRNIVNNTDSPTLKTKTGFLN" +
            "LREFTFEDTKSLDEKKSTIDGLEKNYDNKENQESEYESTKKLDNSLDASSEANNYDITTRKKHSSCNHKI" +
            "KQAVVRPASGRISISRVQSIAITPTKELSIVDPEQNKSNSVIEEISEIEPLNLEYNKKSALYSDTSSTVI" +
            "SISTSKLFESAQNSPLKQTQNPQREFPNGTSVSETNRIRLSIAPTIESVVSDLNSITTGSTVETFETSRD" +
            "LPVPHQRIINLREEYQRGNQDIISNTSSLHELKTIDLSDSNNDLESPSTHAKNNKYFFSPDDGSIDVASP" +
            "MKNVEELKSKFLKNESETNSNISGSVLTMDDIDINDTSSARNTRRANSESAFTGSLNKKNLNEIANMLDD" +
            "SINDDPITVALMKLEGTYEKIPEKPENTKSSDAIGIKTSKLADEVEMLNLNNLPSFQNSPAEKRKSLLIE" +
            "RRRQTIMNIPFTPDQSEKEGFTSSSPEKIDVSANVDVAVQAAQIQELIGQYRIHDSRLMISNNESHVPFI" +
            "LMYDSLSVAQQMTLIEKEILGEIDWKDLLDLKMKHEGPQVISWLQLLVRNETLSGIDLAISRFNLTVDWI" +
            "ISEILLTKSSKMKRNVIQRFIHVADHCRTFQNFNTLMEIILA";
    public static void main(String[] args) {
        Query query = new Query("test header", SEQ);
        ORF newOrf = new ORF(50, 600);
        query.addOrfList(newOrf);
        proteinBlast testBlast = new proteinBlast();
        testBlast.proteinBlast(query);
        testBlast.blast();
    }
}
