package blastConnector;

import blastConnetor.NoBlastConnectionException;
import blastConnetor.proteinBlast;
import orFinderApp.ORF;
import orFinderApp.Query;
import org.junit.Before;
import org.junit.Test;

import static org.junit.jupiter.api.Assertions.assertThrows;

public class NoConnectionBlastTest {

    private final String SEQUENCE = "GCGGGGGGGAAGGAACCAACAGGGATTGCCTTAGTAACTGCGAGTGAAGCGGCAAAAGCTCAGATTTGAAACCTGTCGT" +
            "CTTTGGCGATCGGATTGTAATCTGGAGAGACATCTTCTGGCGGACAGCCGGTCCAAGTTCCTTGGAACAGGACGTCGGAGAGGGTGAGAATCCCGTATCTGGC" +
            "CGGTTTGTTCCGCCTTGTGAAGCGTCTTCGACGAGTCGAGTTGTTTGGGAATGCAGCTCAAAGTGGGTGGTAAATTTCATCTAAAGCTAAATATTGGCGAGAG" +
            "ACCGATAGCGCACAAGTAGAGTGATCGAAAGATGAAAAGCACTTTGAAAAGAGAGTCAAAAAGTACGTGAAATTGTTGAAAGGGAAGCGCTTGAGACCAGACT" +
            "CGCGTTGGGGTGATCAGCGGTGCTTCTGTGCCGTGCACTTGCCCCTTCTCGGGCCAGCATCGGTTGCGACGGCGGGATAAAGACCTGAGGAATGTGGCTCCCC" +
            "TCGGGGAGTGTTATAGCCTCGGGTGCAATGCCGCCAGCCGCGACCGAGGACCGCGCTTCGGCTAGGATGCTGGCATAATGGTCTTCAGCGACCCGTCTTGAAA" +
            "ACGGACCAAGGAGTCTAACATCTATGCGAGTGTTCGGGTGTAAAACCCCTGCGCGTAATGAAAGTGAACGGAGGTGGGAACCCTTCACGGGGTGCACCATCGA" +
            "CCGATCCTGATGTCTTCGGATGGATTTGAGTAGGAGCATAGCTGTTGGGACCCGAAAGATGGTGAACTATGCCTGAATAGGGTGAAGCCAGAGGAAACTCTGG" +
            "TGGAGGCTCGCAGCGGTTCTGACGTGCAAATCGATCGTCAAATTTGGGTATAGGGGCGAAAGACTAATCGAACCATCTAGTAGCTGGTTCCTGCCGAAGTTTC" +
            "CCCCTCCAGGAA";


    private Query query;
    private ORF newOrf;
    private proteinBlast testBlast;

    @Before
    public void setQuery() {
        this.query = new Query("test header", SEQUENCE);
        this.newOrf = new ORF(200, 400);
        this.query.addOrfList(this.newOrf);
        this.testBlast = new proteinBlast();
    }


    @Test
    public void blastSequence() {
        assertThrows(NoBlastConnectionException.class, () -> testBlast.blast(query));
    }

}
